
[project]
authors = [{ name = "yaleman", email = "james@terminaloutcomes.com" }]
requires-python = "<4.0,>=3.12"
dependencies = [
    "schedule>=1.2.2",
    "pygoodwe>=0.1.9",
    "pvoutput>=0.0.11",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
]
name = "goodwe2pvoutput"
version = "0.2.0"
description = "Goodwe to PVOutput"

[dependency-groups]
dev = [
    "pytest>=8.3.5,<10.0.0",
    "mypy>=1.10.0,<2.0",
    "pyright>=1.1.400",
    "ruff>=0.11.8",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pyright]
exclude = ["layer_requirements/**", ".venv/**", ".terraform/**"]
